Article sur l'injection HTML, premiere version
Yt-trium/sizeof-eu pull request #1
Opened 2018-07-30 19:36 UTC by oktomus

2018-07-30 19:39 UTC, oktomus commented on posts/2018/07/hack-old-web-map-viewer.md
> +https://developers.google.com/maps/documentation/javascript/error-messages#unsupported-browsers
Enlever cette ligne

2018-07-31 11:51 UTC, Yt-trium requested changes

2018-07-31 11:51 UTC, Yt-trium commented on _config.yml
> +exclude : [ README.md , CNAME ]
Useless si tu supprime README.md

2018-07-31 11:51 UTC, Yt-trium commented on _config.yml
> +title: Dev blog | Sizeof.eu
sizeof.eu

2018-07-31 11:51 UTC, Yt-trium commented on _config.yml
> +description: Blog de dev français.
Bof mais je trouve pas mieux

2018-07-31 11:51 UTC, Yt-trium commented on index.md
> +### Corriger une erreur de script sur une vielle application Windows
Correction de code HTML dans les ressources d'une application windows obsolète.

2018-07-31 11:51 UTC, Yt-trium commented on index.md
> +### Corriger une erreur de script sur une vielle application Windows
A mon avis supprime toute les modification a index.md et je crée un index générale.

2018-07-31 11:51 UTC, Yt-trium commented on posts/2018/07/hack-old-web-map-viewer.md
> +# Corriger une erreur de script sur une vielle application Windows
Voir index.md + changer le chemin : ./2018/correction-code-html-ressources-application-obsolete ?

2018-07-31 11:51 UTC, Yt-trium commented on posts/2018/07/hack-old-web-map-viewer.md
> +Je vais vous expliquer comment je me suis débrouillé pour corriger un problème bloquant sur un vieux logiciel Windows non mis à jour.
non mis a jours -> obsolete

2018-07-31 11:51 UTC, Yt-trium commented on posts/2018/07/hack-old-web-map-viewer.md
> +Le plus compliqué reste à injecter ce morceau de code dans le logiciel. Dans le cas de *GPS Master*, vous pouvez voir en ouvrant *GPS Master.exe* avec un éditeur qu'il y a de l'*HTML* directement lis
La on rentre dans les problemes techniques.
On injcete rien, on edit des bout de code html utilise par le logiciel et stocké dans ces ressources. Ressource Hacker est un éditeur de ressource.

2018-07-31 12:02 UTC, oktomus commented on _config.yml
> +exclude : [ README.md , CNAME ]
Je vais le supprimer entièrement, sauf si il y a des choses que tu veuille mettre ?

2018-07-31 12:03 UTC, oktomus commented on posts/2018/07/hack-old-web-map-viewer.md
> +# Corriger une erreur de script sur une vielle application Windows
Ca marche

2018-07-31 12:03 UTC, oktomus commented on posts/2018/07/hack-old-web-map-viewer.md
> +Le plus compliqué reste à injecter ce morceau de code dans le logiciel. Dans le cas de *GPS Master*, vous pouvez voir en ouvrant *GPS Master.exe* avec un éditeur qu'il y a de l'*HTML* directement lis
ok !

2018-07-31 12:03 UTC, Yt-trium commented on _config.yml
> +exclude : [ README.md , CNAME ]
ok

2018-07-31 13:45 UTC, Yt-trium approved these changes

2018-07-31 13:46 UTC, Yt-trium requested changes

2018-07-31 13:46 UTC, Yt-trium commented on _config.yml
> +theme: jekyll-theme-midnight
Tu voulais pas supprimer ces changements ?

2018-07-31 13:46 UTC, Yt-trium commented on index.md
> +### Correction de code HTML dans les ressources d'une application Windows obsolète
Et ne pas toucher a l'index ?

2018-07-31 14:09 UTC, oktomus commented on _config.yml
> +theme: jekyll-theme-midnight
Je les ai mis dans un autre commit

2018-07-31 14:09 UTC, oktomus commented on index.md
> +### Correction de code HTML dans les ressources d'une application Windows obsolète
Si pour au moins avoir un lien vers l'article en attendant que tu fasse l'index générique

2018-07-31 14:10 UTC, Yt-trium approved these changes

2018-07-31 14:10 UTC, merged